services:

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile

    container_name: erum-front

    ports:
      - "4241:80"

    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Back/Dockerfile

    container_name: erum-api

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Production

      ConnectionStrings__DefaultConnection: >
        Host=2.25.180.118;
        Port=5433;
        Database=dbErum_QA;
        Username=postgres;
        Password=admin

      Settings__SecretKey: 8b823b3e5baee5baeuKQ22CeUs49tOvR
      Settings__JwtIssuer: ErumApi
      Settings__JwtAudience: ErumFront

    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dbErum_QA

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: